framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en
    translator:
        enabled: true
        fallbacks: ['en']
        default_path: '%kernel.project_dir%/translations'
        logging: true
    session:
        enabled: true
        handler_id: ~

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file