# config/packages/translation.yaml
framework:
    default_locale: en
    translator:
        enabled: true
        fallbacks: ['pl']
        default_path: '%kernel.project_dir%/translations'
        providers: